version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - FLASK_DEBUG=True
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8001
      - MAX_TEXT_LENGTH=1000
      - RATE_LIMIT_STORAGE_URL=redis://redis:6379
      - RATE_LIMIT_PER_MINUTE=100
      - RATE_LIMIT_PER_HOUR=1000
      - CSRF_ENABLED=False
      - FLASK_SECRET_KEY=dev-key-not-for-production
    volumes:
      - ..:/app
    depends_on:
      - redis
    restart: unless-stopped
    
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: 