version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
      - DEPLOYMENT_TYPE=docker
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8001
      - MAX_TEXT_LENGTH=1000
      - RATE_LIMIT_STORAGE_URL=memory://
      - RATE_LIMIT_PER_MINUTE=1000
      - RATE_LIMIT_PER_HOUR=10000
      - ORIGIN_PROTECTION_ENABLED=False
    volumes:
      - ..:/app
    restart: unless-stopped
    
  # Remove Redis for development - not needed with memory storage
  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: 